
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kshxltithvqwjewfhcgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzaHhsdGl0aHZxd2pld2ZoY2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MDA4NDcsImV4cCI6MjA2MjI3Njg0N30.AMpeg1IOQVu5laC395nJtcV_hGt73qhIxKbP69hIkz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
